use_frameworks!

platform :ios, '8.0'

target 'Whiteboard-iOS-Demo_Example' do
  pod 'Whiteboard-iOS-Demo', :path => '../'

  target 'Whiteboard-iOS-Demo_Tests' do
    inherit! :search_paths

    
  end
end
